### ISSUE TITLE
Layout/interface ideas

### ISSUE THREAD

**Issue by DoctorVanGogh** [Killface1980/StorageSearch#10]
So, now that the embeddable assembly idea works it's time to talk about layout and public interfaces.

# Layout 

### Vanilla ThingFilter
![thingfilter](https://user-images.githubusercontent.com/324067/28494222-1c72fc80-6f28-11e7-8377-d7c3d5f03858.png)

### Current 'ImprovedFilter' UI
![thingfilter with search](https://user-images.githubusercontent.com/324067/28494233-66c05364-6f28-11e7-84ef-5d1e5d171bc2.png)

Someone pointed out the allow/clear all buttons were used quite extensively and might thus be a little to small. Also ~~might~~ would need better icons.

### Suggested alternate layout 
![thingfilter with search alternate](https://user-images.githubusercontent.com/324067/28494243-ab1646d6-6f28-11e7-8d34-f623665e5831.png)
- allow/clear all buttons are more prominent
- Search is somewhat smallish. Might not be that big of a problem though, since searches with more than 4-5 characters are rare

### 'Bottom' layout
![thingfilter with search bottom](https://user-images.githubusercontent.com/324067/28494251-fbede3e8-6f28-11e7-9d91-4ff01e9b0cbb.png)
Someone suggested putting the search on the bottom. While this leaves ample space for both the default buttons and search, I personally do not like this. It eats up more vertical space (and might look weird with hysteresis below that), and also I just dont like the workflow. The filter tree is a result of the search clause, thus I'd expect the input parameter above the result. Yes, you might be able to put `supercalifragilisticexpialidocious` into the search without any clipping - I just don't see the use case for that 😉 

---

My personal vote goes to the 'alternate layout' with the big textual buttons and the 30%-ish wide search box on the top right.

# Public interface

Currently the assembly exposes a minimum of types & methods publicly:
```csharp
// encapsulates a search term. A term's textual value (not exposed) is cached and visible again, once it's reused.
public class SearchTerm {
    public string CategoryKey;		// unique ID for this SearchTerm
	
    public void Reset();			// resets/emtpies this SearchTerm's value
}

// allows access to/creation of (cached) SearchTerm
public static class SearchCategories {
	public static SearchTerm TermFor(string category);					// get's a (cached) SearchTerm for an arbitrary key
	
	public static SearchTerm Storage { get; }							// a predefined search term for Storage
	public static SearchTerm Bill { get; }								// a predefined search term for Bills
	public static SearchTerm Outfit { get; }							// a predefined search term for Outfits
}

// Main interaction class for seach injection
public static class ThingFilterUtil {

	// needs to be called *per frame* to inject search for a specific term
    public static void QueueNextInvocationSearch(SearchTerm term, string watermark = null) {
		
}
``` 
Any ideas on required additional features are welcome.

**Comment by Skullywag** [comment]
Personally i like keeping the 2 buttons but i feel the reduced size of the search box is a negative, what I would do would be to add a magnifying glass icon to the right of the 2 buttons (way better fit) which when clicked toggles a search box (possibly floating) and auto sets focus to it, clicking the magnifying glass again would close said search box. With auto focus the number of clicks is the same.

**Comment by tommargar** [comment]
Suggestion
+ 4 Buttons
++ Clear All | Allow All | margin | Clear Visible | Allow Visible
+ Search field below
+ Possibly add cache for search strings
+ Possibly add auto-complete

**Comment by DoctorVanGogh** [comment]
Just for posterity:

Implementation is now configurable:
![image](https://user-images.githubusercontent.com/324067/29089779-bdb416e4-7c7d-11e7-89a7-1f73a02bf428.png)

![image](https://user-images.githubusercontent.com/324067/29089785-ca7fa348-7c7d-11e7-8a35-a0ee6050d816.png)

default is 40%
