### ISSUE TITLE
Compatability with HSK.

### ISSUE THREAD

**Issue by CJoker3221** [Killface1980/StorageSearch#18]
Kinda noticing how the pots/barrels/chests/any kinds of storage in HSK don't play well with the mod. It is a very useful mod, especially the Bill search. Wondering if you could make it compatible in a way?

**Comment by DoctorVanGogh** [comment]
- define "don't play well"
- please elaborate on which _specific_ mods from HSK exhibit the undesired behavior

**Comment by CJoker3221** [comment]
Sorry bout that. In HSK, there are barrels and pots, which are part of the Core of SK. In the modpack, the barrels can store about 6 stacks of items before being full. So basically 6 cells/tiles of item in one tile. But with RSA on, the barrels/pots/chest just stops working, only storing one stack of item. For example, usually I can store up to 450 Milk in one pot but with the mod on, I can only store 75.

**Comment by DoctorVanGogh** [comment]
This probably needs input from @skyarkhangel 😁

**Comment by CJoker3221** [comment]
True I suppose, oh well..I really like the Bill search :c

**Comment by DoctorVanGogh** [comment]
workaround attempt no 1:
- delete `StorageSearch.dll` from `Mods\Core_Sk\Assemblies`

**Comment by CJoker3221** [comment]
Well, I'll try that. I did see Sky doing stuff with this mod on Discord, which is a good thing! :o

**Comment by CJoker3221** [comment]
Hm sadly, even after deleting that dll file, it's still having issues. Does it need a new save?

**Comment by DoctorVanGogh** [comment]
solved in latest commit for 1.0
