### ISSUE TITLE
Separate search strings

### ISSUE THREAD

**Issue by tommargar** [Killface1980/StorageSearch#6]
I noticed that it's a little awkward when searching for e.g. steel in the storage, and when editing outfits finding an empty window.
 
+ keep the search string in the storage consistent, and 
+ clear separate string for new windows like bills and outfit

What do you think?

**Comment by DoctorVanGogh** [comment]
Yeah, it's on my 'minor issues to look at' list.

Do we want to clear search strings between searches? Keep different search strings for each type of search? Or only special case Outfits?
Personally I'd vote for the 'three different search strings' version.

**Comment by tommargar** [comment]
From my experience / preferences as a player, I suggest:
+ keep the storage string consistent throughout the storage zones
+ separate string for everything else
+ separate strings are cleared upon opening a new windows (i.e. outfit, bill) to avoid confusion of empty bills/gear

Another idea: with Vegetable Garden and Apparello, the Plant Grow list becomes rather full, respectively the tailor stuff or any other float menu bill. Fluffy's working on a production menu as replacement for the Production tab in his Colony Manager. Maybe have a look at the plant menu first and see what's possible?

**Comment by DoctorVanGogh** [comment]
Phew - filters on float menus sound "interesting".... No idea if those could be done. (I'd expect "weird" focus auto-close behavior with menus, no idea if we could anchor an input control in there).

Regarding Fluffy's production thing: That was one of the reasons why I'm favoring the 'external assembly' thing. It would have been another place to slap in search boxes ;)

**Comment by tommargar** [comment]
I can help out with the float menu thing. A view of the produceable things sorted by body part was actually working in the Outfitter mod, till some recipes from other mods had null fields. 
I have some experience with float menu options and can take a look at it. I'm currently very busy with Tools For Haul …

**Comment by DoctorVanGogh** [comment]
Funny - my only [experience with float menus](https://github.com/DoctorVanGogh/ExtendedStorage/blob/master/Source/ExtendedStorage/Patches/FloatMenuMakerMap_AddHumanlikeOrders.cs) is limited.

Oh well, I went ahead and chopped the mod into two assemblies. I think we can close #7 then :grin:

Take a look at my [library branch](https://github.com/DoctorVanGogh/StorageSearch/tree/library).  

_And yeah, I snuck that RimworldInstall.props back in there - if you can't get it to work by editing [this path](https://github.com/DoctorVanGogh/StorageSearch/blob/library/Source/RimworldInstall.props#L4) I'll chop it back out before merging. It's just two projects now, each with two assembly references that will create noise on commits from different machines._

Moved StorageSearch into it's own project directory, added a `SearchFilter`project aside it. Moved some options & strings around. 
The Idea is to bundle 
- [Languages\English\Keyed\SearchFilterKeys.xml](https://github.com/DoctorVanGogh/StorageSearch/blob/library/Languages/English/Keyed/SearchFilterKeys.xml)
- [Assemblies\_harmonycheck.dll](https://github.com/DoctorVanGogh/StorageSearch/blob/library/Assemblies/_harmonycheck.dll)
- [Assemblies\0Harmony.dll](https://github.com/DoctorVanGogh/StorageSearch/blob/library/Assemblies/0Harmony.dll)
- [Assemblies\SearchFilter.dll](https://github.com/DoctorVanGogh/StorageSearch/blob/library/Assemblies/SearchFilter.dll)


together with some kind of `HOWTO.md` into a zip and publish that as an embeddable DEV release here on github.

---

On a somewhat different topic: Have you ever taken a look at [VisualStudio Code](https://code.visualstudio.com/) for general mod editing (Still need VS201x itself for assembly builds)?

![image](https://user-images.githubusercontent.com/324067/27766126-0b6039d4-5ec6-11e7-9068-62eafec38c6c.png)

I find it a lot more accessible than reintegrating hardlinks for language defs or preview/about stuff down to assembly projects.

**Comment by DoctorVanGogh** [comment]
Did some nice UI improvements while cleaning this up:
![image](https://user-images.githubusercontent.com/324067/27849919-1c7db074-6151-11e7-9ce3-1e41fb6c5487.png)
![image](https://user-images.githubusercontent.com/324067/27849927-356c0cb6-6151-11e7-9dce-491c6ea4e649.png)
![image](https://user-images.githubusercontent.com/324067/27849942-4a45c8ac-6151-11e7-8607-ff390848998d.png)

With the search box __inside__ the filter (and not one extra pixel used :grin:) we need no longer care _where_ the filter is used, and if there are possibly overlapping controls (like in the outfit dialog).

I like this. Your take? 👍 ? 👎 ? ❓ ?

**Comment by tommargar** [comment]
Gorgeous! Maybe add a little space between the buttons, and is it possible to re-add the description? Just looks a little bit naked. Great work!

**Comment by DoctorVanGogh** [comment]
I can easily do more spacing - and the description(s) are already in there (moved to tooltip, since embedding them inline would have required significantly enlarging the buttons).

![image](https://user-images.githubusercontent.com/324067/27880738-5b84a2c6-61c6-11e7-9712-f8ce53516df3.png)

At a later date we can maybe use other icons (was thinking something like Hugs' 'Allow all' icon).
![image](https://user-images.githubusercontent.com/324067/27880910-0271c6c2-61c7-11e7-8cef-c1475c81aaab.png)
But maybe with just two checkmarks/crosses below each other - possibly monochromatic.... Then again - it's only 24x24 pixels of real estate...

Maybe later - I am _way_ slower at drawing icons than writing code. This looks good enough for right now.

**Comment by DingoDjango** [comment]
You should Rect.ContractedBy(1f) or another float for those buttons/filter. Either that or reposition the rects so that the edges don't overlap with the list rect's edge line.

**Comment by DoctorVanGogh** [comment]
They are and they don't - but I'm assuming you'd vote for some padding in there (Fun fact: vanilla has no such padding :grin:)

**Comment by DingoDjango** [comment]
It looks miles better when the visible edges don't overlap. If your definition of "not overlapping" is that the text filter's visible edge line is a pixel or two below the list rect's line it does not make the eye like it better...

**Comment by tommargar** [comment]
yes, icons need more room to breath
