### ISSUE TITLE
Rename/Rebrand steam release

### ISSUE THREAD

**Issue by DoctorVanGogh** [Killface1980/StorageSearch#8]
I think a steam rename would be okay. After all this mod no longer _just_ supports storage searches.

How about something like
- MultiSearch
- **EnhancedSearch**

Also - does it make sense to version tag releases?

**Comment by tommargar** [comment]
Sorry for not posting to this topic till now. I guess a new name is more than adequate, but I can't decide. I will leave it up to you. 
Version tags can be omitted. SS doesn't really need that anymore.
Also, wanted to let you know that I've added you to Git & Steam as collaborator. You should be able to do the same stuff I can. Update as you wish.
